### ISSUE TITLE
Filter turns regular (lists) arrays to associative (hashmaps) array

### ISSUE THREAD

**Issue by nreynis** [cocur/chain#21]
When you filter an array, it may become 'sparse'. PHP deals with this situation by turning it to an associative array:
https://eval.in/916518
```
<?php
$a1 = ['a', 'z', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', 'q', 's', 'd'];
$a2 = ['a', 'z', 'e', 'r', 't', 'y', 'u', 'i', 'o'];

echo json_encode(array_filter($a1, function($i){ return $i != 's'; }));
echo json_encode(array_filter($a2, function($i){ return $i != 's'; }));
```
```
{"0":"a","1":"z","2":"e","3":"r","4":"t","5":"y","6":"u","7":"i","8":"o","9":"p","10":"q","12":"d"}
["a","z","e","r","t","y","u","i","o"]
```

This is really disturbing and unintuitive, no other language (AFAIK) do that. I know PHP always had this permanent confusion between lists and maps, but this doesn't feel right: if I filter a list I should get a filtered list in return.

Would you consider adding a boolean argument `forceList` or adding a `filterList` method who always return `array_values` in the internal state ?

**Comment by florianeckerstorfer** [comment]
Yes, I would add such a functionality. Since PHP can filter both maps and lists I would prefer if we add an additional function `filterList()`, to make the behavior more clear.

**Comment by nreynis** [comment]
Another more versatile solution would be to add a `keys` and `values` method. So you can do something like:
```php
$chain->filter(...)->values()->array;
```
