### ISSUE TITLE
Tooling needs an update, automated testing fails.

### ISSUE THREAD

**Issue by nreynis** [cocur/chain#38]
Tooling is out of date and cause tests to fail:

- travis for HHVM fails because composer dropped support:
  https://github.com/composer/composer/issues/8127
  You should probably drop it too.
- travis for nightly fails because there´s currently no stable release of phpUnit supporting PHP8
  IMHO you should temporarly disable nightly and update to current phpUnit release
- appveyor fails because php version has been bumped from 7.2 to 7.3

If you want I can take some time to provide a PR.

**Comment by florianeckerstorfer** [comment]
Yes, fixed in #40
