### ISSUE TITLE
Fill is a static factory function it should be moved to Chain

### ISSUE THREAD

**Issue by nreynis** [cocur/chain#48]
Fill is actually a Trait.
https://github.com/cocur/chain/blob/master/src/Link/Fill.php

This is the only Trait that don't operate on an instance and also the only one that is static.  
Other Traits are all instance methods, this one is a factory.  

 This code should be moved to the Chain class which host other factory methods `create` and `createFormString`. This would be an entirely transparent change, it would make the code more consistent and would prevent statistical analysis failing:

https://scrutinizer-ci.com/g/cocur/chain/inspections/fba87ae0-dc03-4190-966a-64fd5f908b9b/issues/files/src/Link/Fill.php?status=all&orderField=path&order=asc&honorSelectedPaths=0

**Comment by florianeckerstorfer** [comment]
Fixed in #49
